language: python

python:  
  - "3.6"

# install the package your need
install:
 - pip install numpy                                                                                                                                                                                                               
 - pip install matplotlib 
 - pip install scipy


before_script: # configure a headless display to test plot generation
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
 - sleep 3 # give xvfb some time to start
 
  
  
# command to run your tests code
script:
  - python hw01.py 

# send notification to your email
notifications:
  email:
    recipients:
      - chenshen.lu@ufl.edu
    on_success: change 
    on_failure: always
